# Generated by Django 6.0 on 2026-08-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, help_text='Unique Product ID', max_length=10, null=True, unique=True),
        ),
    ]
