# Generated by Django 6.0.7 on 2026-09-01 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_contactinquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='Check this when QR payment is verified or COD is collected.'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('QR', 'Paid via QR Code')], default='COD', max_length=20),
        ),
    ]
