# Generated by Django 6.0.7 on 2026-09-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_is_paid_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='Check this when PhonePe payment is verified or COD is collected.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('PHONEPE', 'PhonePe UPI')], default='COD', max_length=20),
        ),
    ]
