# Generated by Django 6.0.7 on 2026-09-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_order_is_paid_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mobile_number',
            field=models.CharField(default='', max_length=20),
        ),
    ]
